<?php
/**
 */

namespace execut\menu\bootstrap;


use execut\actions\Bootstrap;
use execut\crud\navigation\Configurator;
use execut\navigation\Component;
use yii\helpers\ArrayHelper;

class Backend extends Frontend
{
    public function getDefaultDepends() {
        return ArrayHelper::merge(parent::getDefaultDepends(), [
            'bootstrap' => [
                [
                    'class' => Bootstrap::class,
                ]
            ],
        ]); // TODO: Change the autogenerated stub
    }

    /**
     * @param \yii\base\Application $app
     */
    public function bootstrap($app)
    {
        parent::bootstrap($app);
        $this->bootstrapNavigation($app);

    }

    /**
     * @param $app
     */
    protected function bootstrapNavigation($app)
    {
        if ($app->user->isGuest) {
            return;
        }

        /**
         * @var Component $navigation
         */
        $navigation = $app->navigation;
        $models = [
            'menu',
            'item',
            'position',
        ];
        foreach ($models as $model) {
            $navigation->addConfigurator([
                'class' => Configurator::class,
                'module' => 'menu',
                'moduleName' => 'Menu',
                'modelName' => ucfirst($model),
                'controller' => $model . 's',
            ]);
        }
    }
}