<?php
/**
 */

namespace execut\menu\bootstrap;


use execut\actions\Bootstrap;
use execut\crud\navigation\Configurator;
use execut\menu\models\Item;
use execut\menu\models\Menu;
use execut\menu\models\Position;
use execut\navigation\Component;
use yii\helpers\ArrayHelper;

class Backend extends Frontend
{
    public function getDefaultDepends() {
        return ArrayHelper::merge(parent::getDefaultDepends(), [
            'bootstrap' => [
                [
                    'class' => Bootstrap::class,
                ]
            ],
        ]); // TODO: Change the autogenerated stub
    }

    /**
     * @param \yii\base\Application $app
     */
    public function bootstrap($app)
    {
        parent::bootstrap($app);
        $this->bootstrapNavigation($app);
        $this->registerTranslations($app);
    }

    public function registerTranslations($app) {
        $app->i18n->translations['execut/menu'] = [
            'class' => 'yii\i18n\PhpMessageSource',
            'sourceLanguage' => 'en-US',
            'basePath' => '@vendor/execut/yii2-menu/messages',
            'fileMap' => [
                'execut/menu' => 'menu.php',
            ],
        ];
    }

    /**
     * @param $app
     */
    protected function bootstrapNavigation($app)
    {
        if ($app->user->isGuest) {
            return;
        }

        /**
         * @var Component $navigation
         */
        $navigation = $app->navigation;
        $models = [
            'menu' => Menu::MODEL_NAME,
            'item' => Item::MODEL_NAME,
            'position' => Position::MODEL_NAME,
        ];
        foreach ($models as $model => $modelName) {
            $navigation->addConfigurator([
                'class' => Configurator::class,
                'module' => 'menu',
                'moduleName' => 'Menus',
                'modelName' => $modelName,
                'controller' => $model . 's',
            ]);
        }
    }
}