<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace execut\menu\models\base;

use Yii;

/**
 * This is the base-model class for table "menu_menus".
 *
 * @property integer $id
 * @property string $created
 * @property string $updated
 * @property string $name
 * @property boolean $visible
 * @property integer $menu_position_id
 *
 * @property \execut\menu\models\Item[] $items
 * @property \execut\menu\models\Position $menuPosition
 * @property string $aliasModel
 */
abstract class Menu extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'menu_menus';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['created', 'updated'], 'safe'],
            [['name', 'menu_position_id'], 'required'],
            [['visible'], 'boolean'],
            [['menu_position_id'], 'default', 'value' => null],
            [['menu_position_id'], 'integer'],
            [['name'], 'string', 'max' => 255],
            [['menu_position_id'], 'exist', 'skipOnError' => true, 'targetClass' => \execut\menu\models\Position::className(), 'targetAttribute' => ['menu_position_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('execut/menu', 'ID'),
            'created' => Yii::t('execut/menu', 'Created'),
            'updated' => Yii::t('execut/menu', 'Updated'),
            'name' => Yii::t('execut/menu', 'Name'),
            'visible' => Yii::t('execut/menu', 'Visible'),
            'menu_position_id' => Yii::t('execut/menu', 'Menu Position ID'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getItems()
    {
        return $this->hasMany(\execut\menu\models\Item::className(), ['menu_menu_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMenuPosition()
    {
        return $this->hasOne(\execut\menu\models\Position::className(), ['id' => 'menu_position_id']);
    }


    
    /**
     * @inheritdoc
     * @return \execut\menu\models\queries\MenuQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \execut\menu\models\queries\MenuQuery(get_called_class());
    }


}
