<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace execut\menu\models\base;

use Yii;

/**
 * This is the base-model class for table "menu_positions".
 *
 * @property integer $id
 * @property string $created
 * @property string $updated
 * @property string $name
 * @property string $key
 * @property boolean $visible
 *
 * @property \execut\menu\models\Menu[] $menus
 * @property string $aliasModel
 */
abstract class Position extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'menu_positions';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['created', 'updated'], 'safe'],
            [['name', 'key'], 'required'],
            [['visible'], 'boolean'],
            [['name', 'key'], 'string', 'max' => 255],
            [['key'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('execut/menu', 'ID'),
            'created' => Yii::t('execut/menu', 'Created'),
            'updated' => Yii::t('execut/menu', 'Updated'),
            'name' => Yii::t('execut/menu', 'Name'),
            'key' => Yii::t('execut/menu', 'Key'),
            'visible' => Yii::t('execut/menu', 'Visible'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMenus()
    {
        return $this->hasMany(\execut\menu\models\Menu::className(), ['menu_position_id' => 'id']);
    }


    
    /**
     * @inheritdoc
     * @return \execut\menu\models\queries\PositionQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \execut\menu\models\queries\PositionQuery(get_called_class());
    }


}
