<?php
/**
 */

namespace execut\menu\models;


use yii\db\ActiveRecord;

class PagesPage extends ActiveRecord
{
    public static function tableName()
    {
        $pagesTable = \execut\menu\dependencies\Outer::getInstance()->getTable(PagesPage::class);

        return $pagesTable->tableName; // TODO: Change the autogenerated stub
    }
}